# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  docker: circleci/docker@2.2.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: "Start Service and Check That it’s Running"
          command: |
            docker run --rm -it curlimages/curl 'https://api64.ipify.org?format=json'
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t test/circleci-demo-docker:$TAG .
          docker images

workflows:
  example-workflow:
    jobs:
      - example-job
